/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: ef413b7a13796d992d01681aa21ff470)
interface __BaseEnv_CloudflareBindings {
	GITHUB_OWNER: "Andrewegao";
	GITHUB_REPO: "v3t7kq-cycle";
	GITHUB_WORKFLOW: "catalog-bake.yml";
	GITHUB_REF: "main";
	CATALOG_TARGET: "production";
	GITHUB_DISPATCH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_WORKFLOW" | "GITHUB_REF" | "CATALOG_TARGET" | "GITHUB_DISPATCH_TOKEN">> {}
}
